# Admin datasources â€” query the "central" tenant (stack self-monitoring)
# Per-client datasources are created by scripts/deploy_tenant.sh

apiVersion: 1

datasources:
  - name: Mimir (central)
    type: prometheus
    uid: mimir-central
    url: http://mimir:9009/prometheus
    access: proxy
    isDefault: true
    jsonData:
      httpHeaderName1: X-Scope-OrgID
    secureJsonData:
      httpHeaderValue1: central

  - name: Loki (central)
    type: loki
    uid: loki-central
    url: http://loki:3100
    access: proxy
    jsonData:
      httpHeaderName1: X-Scope-OrgID
    secureJsonData:
      httpHeaderValue1: central

  - name: Tempo (central)
    type: tempo
    uid: tempo-central
    url: http://tempo:3200
    access: proxy
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      tracesToLogsV2:
        datasourceUid: loki-central
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
    secureJsonData:
      httpHeaderValue1: central
