global:
  scrape_interval: 15s
  external_labels:
    client: "{{CLIENT_NAME}}"

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
  
  - job_name: 'process_exporter'
    static_configs:
      - targets: ['localhost:9256']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']

remote_write:
  - url: "{{MIMIR_URL}}"
    headers:
      X-Scope-OrgID: "{{CLIENT_NAME}}"
